version: '3.6'

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.15.9
    restart: unless-stopped
    env_file:
      - env/.env.urls
      - env/.env.gitea
    ports:
      - "3000:3000"
      - "222:222"
    networks:
      - cicd_net
    volumes:
      - ./gitea:/data
      - ./certs:/data/certs
      # - ./gpg:/home/git/.gnupg:ro

  drone:
    container_name: drone
    image: drone/drone:2.7.3
    restart: unless-stopped
    depends_on:
      - gitea
    env_file:
      - env/.env.urls
      - env/.env.drone_common
      - env/.env.drone_oauth
      - env/.env.drone_server
    ports:
      - "3001:80"
      - "3002:9000"
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data
      - ./certs:/data/certs

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1.8.0
    restart: unless-stopped
    env_file:
      - env/.env.drone_common
      - env/.env.drone_runner
    depends_on:
      - drone
    ports:
      - "3003:3000"
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  cicd_net:
    name: cicd_net
    # external: true
